name: wallet_finder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.6
  device_information: ^0.0.4
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  url_launcher: ^6.2.4
  get: ^4.6.6
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  slide_countdown: ^0.4.0
  dio: ^5.7.0
  font_awesome_flutter: ^10.8.0
  intl: ^0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/superhanter.jpeg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/superhanter.jpeg"

flutter_native_splash:
  color: "#ffffff" # رنگ پس‌زمینه اسپلش
  image: images/superhanter.jpeg # مسیر لوگوی اسپلش
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true
  assets:
    - images/superhanter.jpeg
  fonts:
    - family: dm
      fonts:
        - asset: fonts/dm.ttf
    - family: vazir
      fonts:
        - asset: fonts/vazir_fd_medium_wol.ttf
